package com.example.demo.persistence;

import java.io.Serializable;

public class MinTbCustomerKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column min_tb_customer.CUSTMER_ID
     *
     * @mbg.generated Sat Mar 17 15:24:38 CST 2018
     */
    private Integer custmerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column min_tb_customer.CUSTMER_USE_ID
     *
     * @mbg.generated Sat Mar 17 15:24:38 CST 2018
     */
    private String custmerUseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table min_tb_customer
     *
     * @mbg.generated Sat Mar 17 15:24:38 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column min_tb_customer.CUSTMER_ID
     *
     * @return the value of min_tb_customer.CUSTMER_ID
     *
     * @mbg.generated Sat Mar 17 15:24:38 CST 2018
     */
    public Integer getCustmerId() {
        return custmerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column min_tb_customer.CUSTMER_ID
     *
     * @param custmerId the value for min_tb_customer.CUSTMER_ID
     *
     * @mbg.generated Sat Mar 17 15:24:38 CST 2018
     */
    public void setCustmerId(Integer custmerId) {
        this.custmerId = custmerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column min_tb_customer.CUSTMER_USE_ID
     *
     * @return the value of min_tb_customer.CUSTMER_USE_ID
     *
     * @mbg.generated Sat Mar 17 15:24:38 CST 2018
     */
    public String getCustmerUseId() {
        return custmerUseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column min_tb_customer.CUSTMER_USE_ID
     *
     * @param custmerUseId the value for min_tb_customer.CUSTMER_USE_ID
     *
     * @mbg.generated Sat Mar 17 15:24:38 CST 2018
     */
    public void setCustmerUseId(String custmerUseId) {
        this.custmerUseId = custmerUseId == null ? null : custmerUseId.trim();
    }
}