package com.example.demo.persistence;

import com.example.demo.mybatis.Page;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class MinTbCustomerExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table min_tb_customer
     *
     * @mbg.generated Sat Mar 17 15:24:38 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table min_tb_customer
     *
     * @mbg.generated Sat Mar 17 15:24:38 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table min_tb_customer
     *
     * @mbg.generated Sat Mar 17 15:24:38 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table min_tb_customer
     *
     * @mbg.generated Sat Mar 17 15:24:38 CST 2018
     */
    protected Page page;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table min_tb_customer
     *
     * @mbg.generated Sat Mar 17 15:24:38 CST 2018
     */
    public MinTbCustomerExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table min_tb_customer
     *
     * @mbg.generated Sat Mar 17 15:24:38 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table min_tb_customer
     *
     * @mbg.generated Sat Mar 17 15:24:38 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table min_tb_customer
     *
     * @mbg.generated Sat Mar 17 15:24:38 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table min_tb_customer
     *
     * @mbg.generated Sat Mar 17 15:24:38 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table min_tb_customer
     *
     * @mbg.generated Sat Mar 17 15:24:38 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table min_tb_customer
     *
     * @mbg.generated Sat Mar 17 15:24:38 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table min_tb_customer
     *
     * @mbg.generated Sat Mar 17 15:24:38 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table min_tb_customer
     *
     * @mbg.generated Sat Mar 17 15:24:38 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table min_tb_customer
     *
     * @mbg.generated Sat Mar 17 15:24:38 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table min_tb_customer
     *
     * @mbg.generated Sat Mar 17 15:24:38 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table min_tb_customer
     *
     * @mbg.generated Sat Mar 17 15:24:38 CST 2018
     */
    public void setPage(Page page) {
        this.page=page;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table min_tb_customer
     *
     * @mbg.generated Sat Mar 17 15:24:38 CST 2018
     */
    public Page getPage() {
        return page;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table min_tb_customer
     *
     * @mbg.generated Sat Mar 17 15:24:38 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCustmerIdIsNull() {
            addCriterion("CUSTMER_ID is null");
            return (Criteria) this;
        }

        public Criteria andCustmerIdIsNotNull() {
            addCriterion("CUSTMER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCustmerIdEqualTo(Integer value) {
            addCriterion("CUSTMER_ID =", value, "custmerId");
            return (Criteria) this;
        }

        public Criteria andCustmerIdNotEqualTo(Integer value) {
            addCriterion("CUSTMER_ID <>", value, "custmerId");
            return (Criteria) this;
        }

        public Criteria andCustmerIdGreaterThan(Integer value) {
            addCriterion("CUSTMER_ID >", value, "custmerId");
            return (Criteria) this;
        }

        public Criteria andCustmerIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("CUSTMER_ID >=", value, "custmerId");
            return (Criteria) this;
        }

        public Criteria andCustmerIdLessThan(Integer value) {
            addCriterion("CUSTMER_ID <", value, "custmerId");
            return (Criteria) this;
        }

        public Criteria andCustmerIdLessThanOrEqualTo(Integer value) {
            addCriterion("CUSTMER_ID <=", value, "custmerId");
            return (Criteria) this;
        }

        public Criteria andCustmerIdIn(List<Integer> values) {
            addCriterion("CUSTMER_ID in", values, "custmerId");
            return (Criteria) this;
        }

        public Criteria andCustmerIdNotIn(List<Integer> values) {
            addCriterion("CUSTMER_ID not in", values, "custmerId");
            return (Criteria) this;
        }

        public Criteria andCustmerIdBetween(Integer value1, Integer value2) {
            addCriterion("CUSTMER_ID between", value1, value2, "custmerId");
            return (Criteria) this;
        }

        public Criteria andCustmerIdNotBetween(Integer value1, Integer value2) {
            addCriterion("CUSTMER_ID not between", value1, value2, "custmerId");
            return (Criteria) this;
        }

        public Criteria andCustmerUseIdIsNull() {
            addCriterion("CUSTMER_USE_ID is null");
            return (Criteria) this;
        }

        public Criteria andCustmerUseIdIsNotNull() {
            addCriterion("CUSTMER_USE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCustmerUseIdEqualTo(String value) {
            addCriterion("CUSTMER_USE_ID =", value, "custmerUseId");
            return (Criteria) this;
        }

        public Criteria andCustmerUseIdNotEqualTo(String value) {
            addCriterion("CUSTMER_USE_ID <>", value, "custmerUseId");
            return (Criteria) this;
        }

        public Criteria andCustmerUseIdGreaterThan(String value) {
            addCriterion("CUSTMER_USE_ID >", value, "custmerUseId");
            return (Criteria) this;
        }

        public Criteria andCustmerUseIdGreaterThanOrEqualTo(String value) {
            addCriterion("CUSTMER_USE_ID >=", value, "custmerUseId");
            return (Criteria) this;
        }

        public Criteria andCustmerUseIdLessThan(String value) {
            addCriterion("CUSTMER_USE_ID <", value, "custmerUseId");
            return (Criteria) this;
        }

        public Criteria andCustmerUseIdLessThanOrEqualTo(String value) {
            addCriterion("CUSTMER_USE_ID <=", value, "custmerUseId");
            return (Criteria) this;
        }

        public Criteria andCustmerUseIdLike(String value) {
            addCriterion("CUSTMER_USE_ID like", value, "custmerUseId");
            return (Criteria) this;
        }

        public Criteria andCustmerUseIdNotLike(String value) {
            addCriterion("CUSTMER_USE_ID not like", value, "custmerUseId");
            return (Criteria) this;
        }

        public Criteria andCustmerUseIdIn(List<String> values) {
            addCriterion("CUSTMER_USE_ID in", values, "custmerUseId");
            return (Criteria) this;
        }

        public Criteria andCustmerUseIdNotIn(List<String> values) {
            addCriterion("CUSTMER_USE_ID not in", values, "custmerUseId");
            return (Criteria) this;
        }

        public Criteria andCustmerUseIdBetween(String value1, String value2) {
            addCriterion("CUSTMER_USE_ID between", value1, value2, "custmerUseId");
            return (Criteria) this;
        }

        public Criteria andCustmerUseIdNotBetween(String value1, String value2) {
            addCriterion("CUSTMER_USE_ID not between", value1, value2, "custmerUseId");
            return (Criteria) this;
        }

        public Criteria andCustmerNameIsNull() {
            addCriterion("CUSTMER_NAME is null");
            return (Criteria) this;
        }

        public Criteria andCustmerNameIsNotNull() {
            addCriterion("CUSTMER_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andCustmerNameEqualTo(String value) {
            addCriterion("CUSTMER_NAME =", value, "custmerName");
            return (Criteria) this;
        }

        public Criteria andCustmerNameNotEqualTo(String value) {
            addCriterion("CUSTMER_NAME <>", value, "custmerName");
            return (Criteria) this;
        }

        public Criteria andCustmerNameGreaterThan(String value) {
            addCriterion("CUSTMER_NAME >", value, "custmerName");
            return (Criteria) this;
        }

        public Criteria andCustmerNameGreaterThanOrEqualTo(String value) {
            addCriterion("CUSTMER_NAME >=", value, "custmerName");
            return (Criteria) this;
        }

        public Criteria andCustmerNameLessThan(String value) {
            addCriterion("CUSTMER_NAME <", value, "custmerName");
            return (Criteria) this;
        }

        public Criteria andCustmerNameLessThanOrEqualTo(String value) {
            addCriterion("CUSTMER_NAME <=", value, "custmerName");
            return (Criteria) this;
        }

        public Criteria andCustmerNameLike(String value) {
            addCriterion("CUSTMER_NAME like", value, "custmerName");
            return (Criteria) this;
        }

        public Criteria andCustmerNameNotLike(String value) {
            addCriterion("CUSTMER_NAME not like", value, "custmerName");
            return (Criteria) this;
        }

        public Criteria andCustmerNameIn(List<String> values) {
            addCriterion("CUSTMER_NAME in", values, "custmerName");
            return (Criteria) this;
        }

        public Criteria andCustmerNameNotIn(List<String> values) {
            addCriterion("CUSTMER_NAME not in", values, "custmerName");
            return (Criteria) this;
        }

        public Criteria andCustmerNameBetween(String value1, String value2) {
            addCriterion("CUSTMER_NAME between", value1, value2, "custmerName");
            return (Criteria) this;
        }

        public Criteria andCustmerNameNotBetween(String value1, String value2) {
            addCriterion("CUSTMER_NAME not between", value1, value2, "custmerName");
            return (Criteria) this;
        }

        public Criteria andCustmerOpertorIsNull() {
            addCriterion("CUSTMER_OPERTOR is null");
            return (Criteria) this;
        }

        public Criteria andCustmerOpertorIsNotNull() {
            addCriterion("CUSTMER_OPERTOR is not null");
            return (Criteria) this;
        }

        public Criteria andCustmerOpertorEqualTo(Integer value) {
            addCriterion("CUSTMER_OPERTOR =", value, "custmerOpertor");
            return (Criteria) this;
        }

        public Criteria andCustmerOpertorNotEqualTo(Integer value) {
            addCriterion("CUSTMER_OPERTOR <>", value, "custmerOpertor");
            return (Criteria) this;
        }

        public Criteria andCustmerOpertorGreaterThan(Integer value) {
            addCriterion("CUSTMER_OPERTOR >", value, "custmerOpertor");
            return (Criteria) this;
        }

        public Criteria andCustmerOpertorGreaterThanOrEqualTo(Integer value) {
            addCriterion("CUSTMER_OPERTOR >=", value, "custmerOpertor");
            return (Criteria) this;
        }

        public Criteria andCustmerOpertorLessThan(Integer value) {
            addCriterion("CUSTMER_OPERTOR <", value, "custmerOpertor");
            return (Criteria) this;
        }

        public Criteria andCustmerOpertorLessThanOrEqualTo(Integer value) {
            addCriterion("CUSTMER_OPERTOR <=", value, "custmerOpertor");
            return (Criteria) this;
        }

        public Criteria andCustmerOpertorIn(List<Integer> values) {
            addCriterion("CUSTMER_OPERTOR in", values, "custmerOpertor");
            return (Criteria) this;
        }

        public Criteria andCustmerOpertorNotIn(List<Integer> values) {
            addCriterion("CUSTMER_OPERTOR not in", values, "custmerOpertor");
            return (Criteria) this;
        }

        public Criteria andCustmerOpertorBetween(Integer value1, Integer value2) {
            addCriterion("CUSTMER_OPERTOR between", value1, value2, "custmerOpertor");
            return (Criteria) this;
        }

        public Criteria andCustmerOpertorNotBetween(Integer value1, Integer value2) {
            addCriterion("CUSTMER_OPERTOR not between", value1, value2, "custmerOpertor");
            return (Criteria) this;
        }

        public Criteria andCustmerAddrIsNull() {
            addCriterion("CUSTMER_ADDR is null");
            return (Criteria) this;
        }

        public Criteria andCustmerAddrIsNotNull() {
            addCriterion("CUSTMER_ADDR is not null");
            return (Criteria) this;
        }

        public Criteria andCustmerAddrEqualTo(String value) {
            addCriterion("CUSTMER_ADDR =", value, "custmerAddr");
            return (Criteria) this;
        }

        public Criteria andCustmerAddrNotEqualTo(String value) {
            addCriterion("CUSTMER_ADDR <>", value, "custmerAddr");
            return (Criteria) this;
        }

        public Criteria andCustmerAddrGreaterThan(String value) {
            addCriterion("CUSTMER_ADDR >", value, "custmerAddr");
            return (Criteria) this;
        }

        public Criteria andCustmerAddrGreaterThanOrEqualTo(String value) {
            addCriterion("CUSTMER_ADDR >=", value, "custmerAddr");
            return (Criteria) this;
        }

        public Criteria andCustmerAddrLessThan(String value) {
            addCriterion("CUSTMER_ADDR <", value, "custmerAddr");
            return (Criteria) this;
        }

        public Criteria andCustmerAddrLessThanOrEqualTo(String value) {
            addCriterion("CUSTMER_ADDR <=", value, "custmerAddr");
            return (Criteria) this;
        }

        public Criteria andCustmerAddrLike(String value) {
            addCriterion("CUSTMER_ADDR like", value, "custmerAddr");
            return (Criteria) this;
        }

        public Criteria andCustmerAddrNotLike(String value) {
            addCriterion("CUSTMER_ADDR not like", value, "custmerAddr");
            return (Criteria) this;
        }

        public Criteria andCustmerAddrIn(List<String> values) {
            addCriterion("CUSTMER_ADDR in", values, "custmerAddr");
            return (Criteria) this;
        }

        public Criteria andCustmerAddrNotIn(List<String> values) {
            addCriterion("CUSTMER_ADDR not in", values, "custmerAddr");
            return (Criteria) this;
        }

        public Criteria andCustmerAddrBetween(String value1, String value2) {
            addCriterion("CUSTMER_ADDR between", value1, value2, "custmerAddr");
            return (Criteria) this;
        }

        public Criteria andCustmerAddrNotBetween(String value1, String value2) {
            addCriterion("CUSTMER_ADDR not between", value1, value2, "custmerAddr");
            return (Criteria) this;
        }

        public Criteria andCustmeTelphoneIsNull() {
            addCriterion("CUSTME_TELPHONE is null");
            return (Criteria) this;
        }

        public Criteria andCustmeTelphoneIsNotNull() {
            addCriterion("CUSTME_TELPHONE is not null");
            return (Criteria) this;
        }

        public Criteria andCustmeTelphoneEqualTo(String value) {
            addCriterion("CUSTME_TELPHONE =", value, "custmeTelphone");
            return (Criteria) this;
        }

        public Criteria andCustmeTelphoneNotEqualTo(String value) {
            addCriterion("CUSTME_TELPHONE <>", value, "custmeTelphone");
            return (Criteria) this;
        }

        public Criteria andCustmeTelphoneGreaterThan(String value) {
            addCriterion("CUSTME_TELPHONE >", value, "custmeTelphone");
            return (Criteria) this;
        }

        public Criteria andCustmeTelphoneGreaterThanOrEqualTo(String value) {
            addCriterion("CUSTME_TELPHONE >=", value, "custmeTelphone");
            return (Criteria) this;
        }

        public Criteria andCustmeTelphoneLessThan(String value) {
            addCriterion("CUSTME_TELPHONE <", value, "custmeTelphone");
            return (Criteria) this;
        }

        public Criteria andCustmeTelphoneLessThanOrEqualTo(String value) {
            addCriterion("CUSTME_TELPHONE <=", value, "custmeTelphone");
            return (Criteria) this;
        }

        public Criteria andCustmeTelphoneLike(String value) {
            addCriterion("CUSTME_TELPHONE like", value, "custmeTelphone");
            return (Criteria) this;
        }

        public Criteria andCustmeTelphoneNotLike(String value) {
            addCriterion("CUSTME_TELPHONE not like", value, "custmeTelphone");
            return (Criteria) this;
        }

        public Criteria andCustmeTelphoneIn(List<String> values) {
            addCriterion("CUSTME_TELPHONE in", values, "custmeTelphone");
            return (Criteria) this;
        }

        public Criteria andCustmeTelphoneNotIn(List<String> values) {
            addCriterion("CUSTME_TELPHONE not in", values, "custmeTelphone");
            return (Criteria) this;
        }

        public Criteria andCustmeTelphoneBetween(String value1, String value2) {
            addCriterion("CUSTME_TELPHONE between", value1, value2, "custmeTelphone");
            return (Criteria) this;
        }

        public Criteria andCustmeTelphoneNotBetween(String value1, String value2) {
            addCriterion("CUSTME_TELPHONE not between", value1, value2, "custmeTelphone");
            return (Criteria) this;
        }

        public Criteria andCustmerFaxIsNull() {
            addCriterion("CUSTMER_FAX is null");
            return (Criteria) this;
        }

        public Criteria andCustmerFaxIsNotNull() {
            addCriterion("CUSTMER_FAX is not null");
            return (Criteria) this;
        }

        public Criteria andCustmerFaxEqualTo(String value) {
            addCriterion("CUSTMER_FAX =", value, "custmerFax");
            return (Criteria) this;
        }

        public Criteria andCustmerFaxNotEqualTo(String value) {
            addCriterion("CUSTMER_FAX <>", value, "custmerFax");
            return (Criteria) this;
        }

        public Criteria andCustmerFaxGreaterThan(String value) {
            addCriterion("CUSTMER_FAX >", value, "custmerFax");
            return (Criteria) this;
        }

        public Criteria andCustmerFaxGreaterThanOrEqualTo(String value) {
            addCriterion("CUSTMER_FAX >=", value, "custmerFax");
            return (Criteria) this;
        }

        public Criteria andCustmerFaxLessThan(String value) {
            addCriterion("CUSTMER_FAX <", value, "custmerFax");
            return (Criteria) this;
        }

        public Criteria andCustmerFaxLessThanOrEqualTo(String value) {
            addCriterion("CUSTMER_FAX <=", value, "custmerFax");
            return (Criteria) this;
        }

        public Criteria andCustmerFaxLike(String value) {
            addCriterion("CUSTMER_FAX like", value, "custmerFax");
            return (Criteria) this;
        }

        public Criteria andCustmerFaxNotLike(String value) {
            addCriterion("CUSTMER_FAX not like", value, "custmerFax");
            return (Criteria) this;
        }

        public Criteria andCustmerFaxIn(List<String> values) {
            addCriterion("CUSTMER_FAX in", values, "custmerFax");
            return (Criteria) this;
        }

        public Criteria andCustmerFaxNotIn(List<String> values) {
            addCriterion("CUSTMER_FAX not in", values, "custmerFax");
            return (Criteria) this;
        }

        public Criteria andCustmerFaxBetween(String value1, String value2) {
            addCriterion("CUSTMER_FAX between", value1, value2, "custmerFax");
            return (Criteria) this;
        }

        public Criteria andCustmerFaxNotBetween(String value1, String value2) {
            addCriterion("CUSTMER_FAX not between", value1, value2, "custmerFax");
            return (Criteria) this;
        }

        public Criteria andCustmeContactIsNull() {
            addCriterion("CUSTME_CONTACT is null");
            return (Criteria) this;
        }

        public Criteria andCustmeContactIsNotNull() {
            addCriterion("CUSTME_CONTACT is not null");
            return (Criteria) this;
        }

        public Criteria andCustmeContactEqualTo(String value) {
            addCriterion("CUSTME_CONTACT =", value, "custmeContact");
            return (Criteria) this;
        }

        public Criteria andCustmeContactNotEqualTo(String value) {
            addCriterion("CUSTME_CONTACT <>", value, "custmeContact");
            return (Criteria) this;
        }

        public Criteria andCustmeContactGreaterThan(String value) {
            addCriterion("CUSTME_CONTACT >", value, "custmeContact");
            return (Criteria) this;
        }

        public Criteria andCustmeContactGreaterThanOrEqualTo(String value) {
            addCriterion("CUSTME_CONTACT >=", value, "custmeContact");
            return (Criteria) this;
        }

        public Criteria andCustmeContactLessThan(String value) {
            addCriterion("CUSTME_CONTACT <", value, "custmeContact");
            return (Criteria) this;
        }

        public Criteria andCustmeContactLessThanOrEqualTo(String value) {
            addCriterion("CUSTME_CONTACT <=", value, "custmeContact");
            return (Criteria) this;
        }

        public Criteria andCustmeContactLike(String value) {
            addCriterion("CUSTME_CONTACT like", value, "custmeContact");
            return (Criteria) this;
        }

        public Criteria andCustmeContactNotLike(String value) {
            addCriterion("CUSTME_CONTACT not like", value, "custmeContact");
            return (Criteria) this;
        }

        public Criteria andCustmeContactIn(List<String> values) {
            addCriterion("CUSTME_CONTACT in", values, "custmeContact");
            return (Criteria) this;
        }

        public Criteria andCustmeContactNotIn(List<String> values) {
            addCriterion("CUSTME_CONTACT not in", values, "custmeContact");
            return (Criteria) this;
        }

        public Criteria andCustmeContactBetween(String value1, String value2) {
            addCriterion("CUSTME_CONTACT between", value1, value2, "custmeContact");
            return (Criteria) this;
        }

        public Criteria andCustmeContactNotBetween(String value1, String value2) {
            addCriterion("CUSTME_CONTACT not between", value1, value2, "custmeContact");
            return (Criteria) this;
        }

        public Criteria andCustmeContactPhoneIsNull() {
            addCriterion("CUSTME_CONTACT_PHONE is null");
            return (Criteria) this;
        }

        public Criteria andCustmeContactPhoneIsNotNull() {
            addCriterion("CUSTME_CONTACT_PHONE is not null");
            return (Criteria) this;
        }

        public Criteria andCustmeContactPhoneEqualTo(String value) {
            addCriterion("CUSTME_CONTACT_PHONE =", value, "custmeContactPhone");
            return (Criteria) this;
        }

        public Criteria andCustmeContactPhoneNotEqualTo(String value) {
            addCriterion("CUSTME_CONTACT_PHONE <>", value, "custmeContactPhone");
            return (Criteria) this;
        }

        public Criteria andCustmeContactPhoneGreaterThan(String value) {
            addCriterion("CUSTME_CONTACT_PHONE >", value, "custmeContactPhone");
            return (Criteria) this;
        }

        public Criteria andCustmeContactPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("CUSTME_CONTACT_PHONE >=", value, "custmeContactPhone");
            return (Criteria) this;
        }

        public Criteria andCustmeContactPhoneLessThan(String value) {
            addCriterion("CUSTME_CONTACT_PHONE <", value, "custmeContactPhone");
            return (Criteria) this;
        }

        public Criteria andCustmeContactPhoneLessThanOrEqualTo(String value) {
            addCriterion("CUSTME_CONTACT_PHONE <=", value, "custmeContactPhone");
            return (Criteria) this;
        }

        public Criteria andCustmeContactPhoneLike(String value) {
            addCriterion("CUSTME_CONTACT_PHONE like", value, "custmeContactPhone");
            return (Criteria) this;
        }

        public Criteria andCustmeContactPhoneNotLike(String value) {
            addCriterion("CUSTME_CONTACT_PHONE not like", value, "custmeContactPhone");
            return (Criteria) this;
        }

        public Criteria andCustmeContactPhoneIn(List<String> values) {
            addCriterion("CUSTME_CONTACT_PHONE in", values, "custmeContactPhone");
            return (Criteria) this;
        }

        public Criteria andCustmeContactPhoneNotIn(List<String> values) {
            addCriterion("CUSTME_CONTACT_PHONE not in", values, "custmeContactPhone");
            return (Criteria) this;
        }

        public Criteria andCustmeContactPhoneBetween(String value1, String value2) {
            addCriterion("CUSTME_CONTACT_PHONE between", value1, value2, "custmeContactPhone");
            return (Criteria) this;
        }

        public Criteria andCustmeContactPhoneNotBetween(String value1, String value2) {
            addCriterion("CUSTME_CONTACT_PHONE not between", value1, value2, "custmeContactPhone");
            return (Criteria) this;
        }

        public Criteria andCreateNameIsNull() {
            addCriterion("CREATE_NAME is null");
            return (Criteria) this;
        }

        public Criteria andCreateNameIsNotNull() {
            addCriterion("CREATE_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andCreateNameEqualTo(String value) {
            addCriterion("CREATE_NAME =", value, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameNotEqualTo(String value) {
            addCriterion("CREATE_NAME <>", value, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameGreaterThan(String value) {
            addCriterion("CREATE_NAME >", value, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_NAME >=", value, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameLessThan(String value) {
            addCriterion("CREATE_NAME <", value, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameLessThanOrEqualTo(String value) {
            addCriterion("CREATE_NAME <=", value, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameLike(String value) {
            addCriterion("CREATE_NAME like", value, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameNotLike(String value) {
            addCriterion("CREATE_NAME not like", value, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameIn(List<String> values) {
            addCriterion("CREATE_NAME in", values, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameNotIn(List<String> values) {
            addCriterion("CREATE_NAME not in", values, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameBetween(String value1, String value2) {
            addCriterion("CREATE_NAME between", value1, value2, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameNotBetween(String value1, String value2) {
            addCriterion("CREATE_NAME not between", value1, value2, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("CREATE_TIME =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("CREATE_TIME <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("CREATE_TIME >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("CREATE_TIME <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("CREATE_TIME in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("CREATE_TIME not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "createTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table min_tb_customer
     *
     * @mbg.generated do_not_delete_during_merge Sat Mar 17 15:24:38 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table min_tb_customer
     *
     * @mbg.generated Sat Mar 17 15:24:38 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}