package com.example.demo.persistence;

import java.io.Serializable;
import java.util.Date;

public class MinTbCustomer extends MinTbCustomerKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column min_tb_customer.CUSTMER_NAME
     *
     * @mbg.generated Sat Mar 17 15:24:38 CST 2018
     */
    private String custmerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column min_tb_customer.CUSTMER_OPERTOR
     *
     * @mbg.generated Sat Mar 17 15:24:38 CST 2018
     */
    private Integer custmerOpertor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column min_tb_customer.CUSTMER_ADDR
     *
     * @mbg.generated Sat Mar 17 15:24:38 CST 2018
     */
    private String custmerAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column min_tb_customer.CUSTME_TELPHONE
     *
     * @mbg.generated Sat Mar 17 15:24:38 CST 2018
     */
    private String custmeTelphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column min_tb_customer.CUSTMER_FAX
     *
     * @mbg.generated Sat Mar 17 15:24:38 CST 2018
     */
    private String custmerFax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column min_tb_customer.CUSTME_CONTACT
     *
     * @mbg.generated Sat Mar 17 15:24:38 CST 2018
     */
    private String custmeContact;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column min_tb_customer.CUSTME_CONTACT_PHONE
     *
     * @mbg.generated Sat Mar 17 15:24:38 CST 2018
     */
    private String custmeContactPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column min_tb_customer.CREATE_NAME
     *
     * @mbg.generated Sat Mar 17 15:24:38 CST 2018
     */
    private String createName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column min_tb_customer.CREATE_TIME
     *
     * @mbg.generated Sat Mar 17 15:24:38 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table min_tb_customer
     *
     * @mbg.generated Sat Mar 17 15:24:38 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column min_tb_customer.CUSTMER_NAME
     *
     * @return the value of min_tb_customer.CUSTMER_NAME
     *
     * @mbg.generated Sat Mar 17 15:24:38 CST 2018
     */
    public String getCustmerName() {
        return custmerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column min_tb_customer.CUSTMER_NAME
     *
     * @param custmerName the value for min_tb_customer.CUSTMER_NAME
     *
     * @mbg.generated Sat Mar 17 15:24:38 CST 2018
     */
    public void setCustmerName(String custmerName) {
        this.custmerName = custmerName == null ? null : custmerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column min_tb_customer.CUSTMER_OPERTOR
     *
     * @return the value of min_tb_customer.CUSTMER_OPERTOR
     *
     * @mbg.generated Sat Mar 17 15:24:38 CST 2018
     */
    public Integer getCustmerOpertor() {
        return custmerOpertor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column min_tb_customer.CUSTMER_OPERTOR
     *
     * @param custmerOpertor the value for min_tb_customer.CUSTMER_OPERTOR
     *
     * @mbg.generated Sat Mar 17 15:24:38 CST 2018
     */
    public void setCustmerOpertor(Integer custmerOpertor) {
        this.custmerOpertor = custmerOpertor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column min_tb_customer.CUSTMER_ADDR
     *
     * @return the value of min_tb_customer.CUSTMER_ADDR
     *
     * @mbg.generated Sat Mar 17 15:24:38 CST 2018
     */
    public String getCustmerAddr() {
        return custmerAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column min_tb_customer.CUSTMER_ADDR
     *
     * @param custmerAddr the value for min_tb_customer.CUSTMER_ADDR
     *
     * @mbg.generated Sat Mar 17 15:24:38 CST 2018
     */
    public void setCustmerAddr(String custmerAddr) {
        this.custmerAddr = custmerAddr == null ? null : custmerAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column min_tb_customer.CUSTME_TELPHONE
     *
     * @return the value of min_tb_customer.CUSTME_TELPHONE
     *
     * @mbg.generated Sat Mar 17 15:24:38 CST 2018
     */
    public String getCustmeTelphone() {
        return custmeTelphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column min_tb_customer.CUSTME_TELPHONE
     *
     * @param custmeTelphone the value for min_tb_customer.CUSTME_TELPHONE
     *
     * @mbg.generated Sat Mar 17 15:24:38 CST 2018
     */
    public void setCustmeTelphone(String custmeTelphone) {
        this.custmeTelphone = custmeTelphone == null ? null : custmeTelphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column min_tb_customer.CUSTMER_FAX
     *
     * @return the value of min_tb_customer.CUSTMER_FAX
     *
     * @mbg.generated Sat Mar 17 15:24:38 CST 2018
     */
    public String getCustmerFax() {
        return custmerFax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column min_tb_customer.CUSTMER_FAX
     *
     * @param custmerFax the value for min_tb_customer.CUSTMER_FAX
     *
     * @mbg.generated Sat Mar 17 15:24:38 CST 2018
     */
    public void setCustmerFax(String custmerFax) {
        this.custmerFax = custmerFax == null ? null : custmerFax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column min_tb_customer.CUSTME_CONTACT
     *
     * @return the value of min_tb_customer.CUSTME_CONTACT
     *
     * @mbg.generated Sat Mar 17 15:24:38 CST 2018
     */
    public String getCustmeContact() {
        return custmeContact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column min_tb_customer.CUSTME_CONTACT
     *
     * @param custmeContact the value for min_tb_customer.CUSTME_CONTACT
     *
     * @mbg.generated Sat Mar 17 15:24:38 CST 2018
     */
    public void setCustmeContact(String custmeContact) {
        this.custmeContact = custmeContact == null ? null : custmeContact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column min_tb_customer.CUSTME_CONTACT_PHONE
     *
     * @return the value of min_tb_customer.CUSTME_CONTACT_PHONE
     *
     * @mbg.generated Sat Mar 17 15:24:38 CST 2018
     */
    public String getCustmeContactPhone() {
        return custmeContactPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column min_tb_customer.CUSTME_CONTACT_PHONE
     *
     * @param custmeContactPhone the value for min_tb_customer.CUSTME_CONTACT_PHONE
     *
     * @mbg.generated Sat Mar 17 15:24:38 CST 2018
     */
    public void setCustmeContactPhone(String custmeContactPhone) {
        this.custmeContactPhone = custmeContactPhone == null ? null : custmeContactPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column min_tb_customer.CREATE_NAME
     *
     * @return the value of min_tb_customer.CREATE_NAME
     *
     * @mbg.generated Sat Mar 17 15:24:38 CST 2018
     */
    public String getCreateName() {
        return createName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column min_tb_customer.CREATE_NAME
     *
     * @param createName the value for min_tb_customer.CREATE_NAME
     *
     * @mbg.generated Sat Mar 17 15:24:38 CST 2018
     */
    public void setCreateName(String createName) {
        this.createName = createName == null ? null : createName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column min_tb_customer.CREATE_TIME
     *
     * @return the value of min_tb_customer.CREATE_TIME
     *
     * @mbg.generated Sat Mar 17 15:24:38 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column min_tb_customer.CREATE_TIME
     *
     * @param createTime the value for min_tb_customer.CREATE_TIME
     *
     * @mbg.generated Sat Mar 17 15:24:38 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}