package com.example.demo.mapper;

import com.example.demo.persistence.MinTbCustomer;
import com.example.demo.persistence.MinTbCustomerExample;
import com.example.demo.persistence.MinTbCustomerKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MinTbCustomerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table min_tb_customer
     *
     * @mbg.generated Sat Mar 17 15:24:38 CST 2018
     */
    long countByExample(MinTbCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table min_tb_customer
     *
     * @mbg.generated Sat Mar 17 15:24:38 CST 2018
     */
    int deleteByExample(MinTbCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table min_tb_customer
     *
     * @mbg.generated Sat Mar 17 15:24:38 CST 2018
     */
    int deleteByPrimaryKey(MinTbCustomerKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table min_tb_customer
     *
     * @mbg.generated Sat Mar 17 15:24:38 CST 2018
     */
    int insert(MinTbCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table min_tb_customer
     *
     * @mbg.generated Sat Mar 17 15:24:38 CST 2018
     */
    int insertSelective(MinTbCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table min_tb_customer
     *
     * @mbg.generated Sat Mar 17 15:24:38 CST 2018
     */
    List<MinTbCustomer> selectByExample(MinTbCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table min_tb_customer
     *
     * @mbg.generated Sat Mar 17 15:24:38 CST 2018
     */
    MinTbCustomer selectByPrimaryKey(MinTbCustomerKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table min_tb_customer
     *
     * @mbg.generated Sat Mar 17 15:24:38 CST 2018
     */
    int updateByExampleSelective(@Param("record") MinTbCustomer record, @Param("example") MinTbCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table min_tb_customer
     *
     * @mbg.generated Sat Mar 17 15:24:38 CST 2018
     */
    int updateByExample(@Param("record") MinTbCustomer record, @Param("example") MinTbCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table min_tb_customer
     *
     * @mbg.generated Sat Mar 17 15:24:38 CST 2018
     */
    int updateByPrimaryKeySelective(MinTbCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table min_tb_customer
     *
     * @mbg.generated Sat Mar 17 15:24:38 CST 2018
     */
    int updateByPrimaryKey(MinTbCustomer record);
}